### ISSUE TITLE
chore: 초기 환경 설정

### ISSUE THREAD

**Issue by jee-woo** [capstone-five-ai/Qtudy-FE#1]
## Description
초기 환경 설정

## To-do

- [x] vite(React + TypeScript) 환경 설정
- [x] styled components 설치 및 설정
- [x] eslint, prettier 설치 및 설정
- [x] recoil 설치 및 폴더 구조 설정
