### ISSUE TITLE
feature: 퀴즈 생성 오른쪽 사이드바 구현

### ISSUE THREAD

**Issue by AAminha** [capstone-five-ai/Qtudy-FE#10]
## Description

퀴즈 생성 페이지 내의 오른쪽 사이드바 구현

## To-do

- [x] 재활용 가능하도록 컴포넌트 구현
  - [x] 문제 설정 컴포넌트 구현 (설정 제목, 라디오 버튼으로 구성된 선택지)
  - [x] 파일명 컴포넌트 구현
  - [x] 버튼 컴포넌트 구현

### 구현할 오른쪽 사이드바 (피그마)
<p align="center">
  <img src="https://github.com/capstone-five-ai/Qtudy-FE/assets/87255791/ec981680-7443-4b03-a4ba-82b9b3be109a" align="center" width="45%">
<img src="https://github.com/capstone-five-ai/Qtudy-FE/assets/87255791/3e36031b-5ffb-4fc9-aaaf-92ba744ca5c8" align="center" width="45%">
</p>

### 컴포넌트 구성 단위
<p align="center">
  <img src="https://github.com/capstone-five-ai/Qtudy-FE/assets/87255791/aa1e0cee-12e2-49e9-b1e9-5b48b1226b16" align="center" width="20%">
<img src="https://github.com/capstone-five-ai/Qtudy-FE/assets/87255791/8810c8a2-be97-427b-bbb6-db9fed65ca13" align="center" width="35%">
<img src="https://github.com/capstone-five-ai/Qtudy-FE/assets/87255791/d26a64ba-1a54-4381-a26a-9cc506a0192a" align="center" width="35%">
</p>
