### ISSUE TITLE
fix: 디자인 피드백 5차 반영

### ISSUE THREAD

**Issue by AAminha** [capstone-five-ai/Qtudy-FE#110]
## Description

5차 디자인 피드백 및 기능 오류 피드백을 반영합니다.

## To-do

- [x] 토스트 메시지 duration 시간 변경
- [x] CTA 버튼 디자인 재조정
- [x] 카테고리 이름 수정 시, placeholder 안보이도록 변경
- [x] 히스토리 파일명 수정 시, 아이콘을 클릭해야 수정 완료되도록 변경
- [x] 이름 변경이 없을 경우 편집 완료가 안되는 문제 해결
- [x] 빈 항목에 대한 디자인 추가
- [x] 폰트 수정 반영
- [x] `파일명 -> 제목` 워딩 수정
