### ISSUE TITLE
feature: 기능 제목

### ISSUE THREAD

**Issue by AAminha** [capstone-five-ai/Qtudy-FE#121]
## Description

디자인 변경사항을 반영합니다.

## To-do

- [ ] main mint medium 반영
- [ ] 카테고리 내 콘텐츠 리스트 디자인 변경
- [ ] 파일 업로드/텍스트 직접 입력 디자인 변경
- [ ] CTA 버튼 디자인 변경
- [ ] 로고 파일 변경
- [ ] 네비바 뒷배경 삭제
- [ ] hover 시 보여졌던 long Arrow 아이콘 삭제
