### ISSUE TITLE
design: 헤더 디자인 변경

### ISSUE THREAD

**Issue by AAminha** [capstone-five-ai/Qtudy-FE#17]
## Description

헤더 디자인 변경

## To-do

- [x] 헤더 메뉴 항목 위치 변경
- [x] 헤더 너비 제한 삭제
- [x] 호버링 디자인 변경
