### ISSUE TITLE
feature: api 연결 및 페이지 이동 기능 구현

### ISSUE THREAD

**Issue by AAminha** [capstone-five-ai/Qtudy-FE#40]
## Description

담당했던 기능 api 연결

## To-do

- [x] 퀴즈 생성
  - [x] AI 퀴즈 생성 - PDF 파일 업로드
  - [x] AI 퀴즈 생성 - 이미지 파일 업로드
  - [x] AI 퀴즈 생성 - 텍스트
  - [x] 자체 퀴즈 생성
  - [x] 생성 후 조회 페이지로
- [x] 요약 생성
  - [x] AI 요약 생성 - PDF 파일 업로드
  - [x] AI 요약 생성 - 이미지 파일 업로드
  - [x] AI 요약 생성 - 텍스트
  - [x] 자체 요약 생성
  - [x] 생성 후 조회 페이지로
- [x] 카테고리
  - [x] 카테고리 목록 조회 (퀴즈, 요약)
  - [x] 카테고리 목록 수정 (퀴즈, 요약)
  - [x] 카테고리 목록 삭제 (퀴즈, 요약)
  - [x] 카테고리 생성 (퀴즈, 요약)
  - [x] 특정 카테고리 PDF 다운로드 (퀴즈PDF, 정답 PDF, 요약 PDF)
  - [x] 특정 카테고리 아이템 목록 조회 (퀴즈, 요약)
  - [x] 특정 카테고리 아이템 삭제 (퀴즈, 요약)
  - [x] 특정 카테고리 아이템 상세 조회 (퀴즈, 요약)
  - [x] 특정 카테고리 아이템 편집 (퀴즈, 요약)
