### ISSUE TITLE
design: 디자인 피드백 반영

### ISSUE THREAD

**Issue by AAminha** [capstone-five-ai/Qtudy-FE#65]
## Description

디자인 피드백 반영

## To-do

- [ ] 네비바
  - [ ] max-width 해제, padding 0px 40px로 변경
- [ ] 툴팁
  - [ ] 등장 인터랙션 필요 (배민의 ‘같이 먹고 싶은 멤버와 함께 골라요’ 툴팁 참고)
  - [ ] 네비바 툴팁 듀레이션 문제
- [ ] CTA
  - [ ] 호버 및 클릭 가능 영역 체크 (‘Generate’버튼과 ‘카테고리 먼저 만들기’버튼 둘 비교)
  - [ ] CTA(small, hover, gray)의 텍스트 컬러 변경 (grayscale02)
  - [ ] CTA(large, hover, mint)의 컬러 변경 (다른 hover, mint버튼과 동일하게 main mint_dark gra)
- [ ] AI 생성
  - [ ] AI 생성 파일or텍스트 선택 -  ‘파일 업로드 또는 텍스트 입력 시…’의 margin-bottom 52px
  - [ ] 요약 생성 ‘파일 업로드 또는 텍스트 입력 시…’의 문구 확인
  - [ ] 썸네일 div의 뒤에 그림자가 잘림
  - [ ] 썸네일div(default)의 opacity 0.8로 변경
  - [ ] 1회 파일 업로드 후 재업로드를 하려면 어떻게 해야하는지? > 나도 궁금
  - [ ] ‘퀴즈를 생성하고 싶은 관련 텍스트를 입력해주세요’ 컬러 확인 (grayscale05)
- [ ] Loader
  - [ ] circle로더의 인터랙션 구현
- [ ] 자체 퀴즈 생성
  - [ ] 자체 퀴즈 생성(default)는 기본적으로 질문과 선지 1개로 구성
  - [ ] 해설 textfield도 비어있을 때는 편집 아이콘이 아니더라도 field를 클릭했을 때 입력할 수 있게 활성화 필요
  - [ ] 자체 퀴즈 생성, 카테고리 퀴즈 편집에서 사용하는 TextField/question(피그마 컴포넌트) width를 모두 724px로 통일
  - [ ] 자체 퀴즈 생성(주관식)의 정답 및 해설에서 객관식 정답div 제외
- [ ] 카테고리
  - [ ] '아직 생성된 카테고리가 없어요' 텍스트 중 제일 마지막 텍스트와 버튼 사이. gap 156px로 변경
  - [ ] 해당 페이지의 default는 피그마 시안대로 ‘카테고리를 추가해주세요’, ‘카테고리를 선택해 주세요’로 보여지고 ‘아직 생성된 퀴즈(요약)이 없어요’는 카테고리 보유하고 있고 선택을 했는데 퀴즈(요약)을 보유하고 있지 않을 경우 보여짐
  - [ ] 왼쪽 사이드바 div의 width, margin-right 각각 324px, 36px (피그마 시안이랑 대조 필요, 내부 div들도 모두 width 324px)
  - [ ] 퀴즈 카테고리 문제와 날짜 사이 gap 14px
  - [ ] hover시 등장하는 Icon/longArrow(피그마 컴포넌트) 컬러 확인 (grayscale05)
  - [ ] 카테고리 내 퀴즈(요약) 리스트UI height값 피그마 시안이랑 차이나는 이유?
  - [ ] 카테고리 내 퀴즈(요약) 리스트UI의 width, height는 피그마에서 설정한대로 fixed, fixed (요약 미리보기가 한 줄이라고해서 리스트UI의 height가 줄어들지 않고 두 줄 공간대로 유지)
