### ISSUE TITLE
design: 디자인 피드백 반영

### ISSUE THREAD

**Issue by AAminha** [capstone-five-ai/Qtudy-FE#86]
## Description
디자인 피드백 반영

## To-do

- [x] 오타 수정 : 문제 유형 -> 퀴즈 유형 => `민하`
- [x] 오타 수정 : 풀어보세요 -> 학습하세요 => `주은`
- [x] 오타 수정 : 퀴츠 => `주은`
- [x] 워딩 수정 : 스플래쉬 `AI가 생성한 퀴즈와 요약으로 효율적인 학습을 돕는` => `주은`
- [x] 기능 수정 : 주관식 퀴즈의 정답 및 해설란에 객관식 정답 영역 제외 => `민하`
- [x] 디자인 및 기능 오류 : '나만의 카테고리에 저장하고 관리할 수 있어요' 모달 피그마 시안과의 차이 보완 => `주은`
- [x] 디자인 및 기능 오류 : 카테고리 리스트 컴포넌트의 Default와 Hover시의 좌측 라인 두께 차이로 인해 hover시 이동하는 느낌 => `민하`
- [x] 디자인 및 기능 오류 : 중복되는 카테고리 알림 - 팝업 -> 하단 텍스트 => `민하`
- [x] 디자인 및 기능 오류 : 파일 이름이 이미 존재할 경우, 로딩 화면 전에 해당 팝업이 뜨도록 할 수 있는지 =>  `민하`
- [x] 디자인 및 기능 오류 : 카테고리 페이지에서 '카테고리 추가' 버튼 컬러 변경 (민트 -> 그레이) => `민하`
- [x] 디자인 및 기능 오류 : 자체 요약 텍스트 박스 피그마 시안과 차이 보완 => `민하`
- [x] 디자인 및 기능 오류 : 텍스트 박스에 일정 양 이상 입력 시 스크롤 바가 2개 생성되는 오류 => `민하`
- [x] 디자인 및 기능 오류 : 웹 상에서 카테고리 내 컨텐츠 상세 페이지에서 '목록으로' 버튼 클릭 시, 해당 카테고리가 선택된 목록으로 돌아가지 않고 카테고리 선택 전으로 돌아갑니다. 카테고리 선택된 목록으로 이동하게끔 수정 => `민하`
- [x] 사용성 개선1 : 카테고리 이름 수정 시, complete 아이콘 추가 + 편집 완료 시에 아이콘 클릭 혹은 화면 빈 부분을 클릭하여 완료 => `민하`
- [x] 사용성 개선2 : CTA (Gray, Small, Hover)의 UI 차이가 명확하지 않아 더 수정했으니 반영 => `민하`
- [x] 추가 : pdf 미리보기 화면 수정 => `민하`
