### ISSUE TITLE
design: 디자인 피드백 4차 반영

### ISSUE THREAD

**Issue by AAminha** [capstone-five-ai/Qtudy-FE#92]
## Description

4월 14일, 15일에 전달받은 디자인 피드백을 반영합니다.

## To-do

- [x] 나만의 카테고리 페이지에서 카테고리 리스트 UI 변경 (padding값 12px, gapX)
- [x] 민트 CTA 버튼 box shadow 이중인지 확인 필요 (민트 CTA hover 시 box shadow 변화X)
- [x] 그레이 CTA 버튼 box shadow 값 수정
- [x] 그레이 CTA 버튼 default는 #757575 -> hover는 #424242
- [x] 카테고리 추가 클릭 없이 바로 input창이 보이도록 수정
- [x] input 상태별 디자인 확인 필요 (default, pressed에서 메시지 확인)
- [x] 나만의 카테고리 페이지에서 카테고리 추가 모달 input에 margin-bottom 2px 필요
- [x] 사용자 퀴즈 생성, 편집 등에서 항목 추가 시, 영역 넘어가는 오류 해결
- [x] 사용자 퀴즈 생성, 편집 등에서 complete 아이콘 삭제
- [x] 사용자 퀴즈 생성, 편집 등에서 delete 아이콘 클릭 시, 토스트 보이도록
- [x] 요약 카테고리 모달에서 퀴즈 카테고리가 보이는 오류 해결
- [x] 카테고리 추가 버튼과 편집, 삭제 아이콘 동일 선상에 위치
- [x] 카테고리 선택 리스트와 상세 리스트 사이 gap 36px
- [x] Pre, Next 리스트 UI 없음
- [x] 요약정리 스크롤 적용 안됨
- [x] ~~객관식 퀴즈에서 정답 라디오 버튼 클릭 시, 3번 항목만 정답 및 해설에 반영되지 않는 오류 해결~~
- [x] 아이콘 hover 컬러 gra로 반영되었는지 확인
- [x] 로딩 화면의 폰트 컬러 generating...(#BDBDBD) -> Complete! (#FFFFFF)로 변경
- [x] 나만의 카테고리에서 워딩 수정 AI -> AI 생성 / 자체 -> 자체 생성
